### ISSUE TITLE
Can't bind to ...

### ISSUE THREAD

**Issue by antonpegov** [NetanelBasal/spectator#114]
Am I missing something, but looks like spectator not mocking pipes and can't mock components with inputs? 
I'm getting Error **Can't bind to 'chartId/chartData/showDefaultPresentationData' since it isn't a known property of 'app-highcharts'** :

>     . . . (my component code)
>      <div class="highcharts-container">
>         <div class="coverage-status-chart">
>           <app-highcharts
>             viewui="coverage-status-chart"
>             [chartId]="'container'"
>             [chartData]="chartData"
>             [showDefaultPresentationData]="showDefaultPresentationData">
>           </app-highcharts>
>         </div>
>       </div>
>     </div>
> 
>     <div class="right-info">
>       <div class="additional-info-area">
>         <div class="additional-detail bil-to-name">
>           <h5 viewui="bill-to-gu-name-label">{{ 'BILLTO_GU_NAME' | labels }}</h5>
>           <h3 viewui="bill-to-gu-name-value">{{ contractsData.billToGuName }}</h3>
>         </div>
>     . . . 

My test: 

>     describe ('Using  Spectator Lib', () => {
>       let host: SpectatorWithHost<ContractAdditionalInformationComponent>;
>       const createHost = createHostComponentFactory({
>       component: ContractAdditionalInformationComponent,
>       declarations: [MockedLabelsPipe] // without this mock Spectator falls with "Can't find the labels" pipe
>     });
> 
>     it('displays provided label', () => {
>       const contractsData = { billToGuName: contractName};
>       host = createHost(`
>         <app-contract-additional-information [contractData] = "contractsData">
>         </app-contract-additional-information>
>       `);
>       host.setInput('contractsData', { billToGuName: contractName} as any);
>       expect(host.query('[viewui = bill-to-gu-name-value]').innerHTML).toContain(contractName);
>     });
>   });

**Comment by benelliott** [comment]
Yes, you need to pass the mocked components and pipes into Spectator's `createHostComponentFactory` method. The recommended way to do this is to use the `ng-mocks` library.

Spectator won't automagically figure out which components need to be mocked, especially since the same component will sometimes need to be mocked in different ways depending on the test.

**Comment by antonpegov** [comment]
Then what is the purpose of Spectator? I thought it was created to automatically mock dependent components, including ones from third-party libraries.

**Comment by benelliott** [comment]
No - it's to reduce the boilerplate you usually have to write when [writing Angular unit tests](https://angular.io/guide/testing#component-test-scenarios).

**Comment by walrus95** [comment]
> No - it's to reduce the boilerplate you usually have to write when [writing Angular unit tests](https://angular.io/guide/testing#component-test-scenarios).

@benelliott @NetanelBasal Well, the problem is that people have been going around saying that the purpose of Spectator is to automatically mock dependencies. The only reason I started looking into Spectator in the first place is because of such claims. For example, [this blog post](https://medium.com/@fivedicephoto/why-you-shouldnt-use-no-errors-schema-in-angular-unit-tests-cdd478c30782) reads:

"[Spectator] reduces the boilerplate into significantly less code **and automatically mocks your dependencies!**"

The whole blog post is about why you shouldn't be using NO_ERRORS_SCHEMA, and should be mocking instead, but don't need to because you can just use Spectator. The author of Spectator @NetanelBasal even responded to the blog post saying: "Thanks, glad you like it."

If Spectator doesn't provide automatic mocking at all, why wasn't the author of Spectator like, "Thanks man, but unfortunately Spectator doesn't do what you think it does. Sorry!"

Is there something I don't understand here? If not, somebody from this project should correct the record on blog posts like that one.

Not trying to be a pain here, just trying to make sure accurate information gets out there for the public, and that my own understanding of this issue is correct. Thanks!

**Comment by benelliott** [comment]
Hi @walrus95, it's a good question worth clarifying.

I think there are multiple factors here:

1) It's not clear from the article exactly what the author means by "automatically mocks your dependencies". It could be interpreted as being that it will magically figure out what needs to be mocked and do so, but actually I think the author is just referring to the mocking shortcuts that Spectator used to provide out of the box: https://github.com/NetanelBasal/spectator/blob/7ae901860704ce50f26f7753b6d6101e83761b2b/projects/spectator/jest/src/spectator.ts#L23
2) In the advent of new libraries like ng-mocks, Spectator has shifted direction slightly since that blog post was written. It no longer offers the aforementioned mocking functionality as these other libraries do it better. This means Spectator can focus on reducing the boilerplate around the Angular unit testing APIs.
3) The original issue was talking about auto-mocking components rather than services. IIRC this is something Spectator never did.
